server:
  port: 8083
  error:
    include-message: always # for validation messages
springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    display-query-params: true
  model-converters:
    pageable-converter:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: postgres
  rabbitmq:
    port: 5672
    host: localhost
  jackson:
    serialization:
      write-dates-as-timestamps: false

banking:
  account:
    queue-name: banking.account
    exchange-name: banking.account
    route-key: banking.account
  transaction:
    queue-name: banking.transaction
    exchange-name: banking.transaction
    route-key: banking.transaction
